### ISSUE TITLE
Roadmap to stable version

### ISSUE THREAD

**Issue by targos** [image-js/image-js#711]
- [x] Minimal documentation with docusaurus with announcement blog post.
  - [x] Create repository
  - [x] Demo page with list of images to select, drag/drop (optional), or webcam (optional) and live script
  - [x] Complex "tutorials" (optional)
  - [x] Live examples on API docs
    - [x] "raw" code
    - [x] fixed code with editable variables/parameters
    - [x] Do no use Lena image by default on demos.
  - [x] Blog post about new TypeScript rewrite with high-level description of the breaking changes.
  - [x] Link to tsdoc
- [x] Review parity of functionality with legacy version.
- [x] Check if API is consistent
- [x] Rewrite changelog in https://github.com/image-js/image-js/pull/729 and enable workflow on https://github.com/image-js/image-js/actions/workflows/release.yml (last thing to do before merge of the release PR)
- [x] Merge with the main repo
- [x] Change release workflow
- [x] Use template typedoc workflow
- [x] Update links in readme
- [x] Publish docs and api docs to image-js.org or image-js.com domains.
- [x] https://github.com/image-js/image-js/issues/737
- [x] https://github.com/image-js/image-js-docs/issues/131
- [x] https://github.com/image-js/image-js-docs/issues/135
- [x] Linkedin post acknowledging contributors and linking to zakodium opensource page on its website.
- [x] Update dep in image-js-docs to use `^1.0.0`
